# -*- coding: utf-8 -*-
"""get valid password.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188bG7x4EUFKGQsoOz36Va1ktE-vt-y7T
"""

import time
import string

username = "Rayan Geroge"
#password = "S1@rWars"

def get_password():
  input_password = input("Password: ")

  while True:
    has_uppercase = False
    has_lowercase = False
    has_number = False
    has_symbol = False

    if len(input_password) <= 4:
      print("Password must be longer than eight characters")
    else:
      for letter in input_password:
          if letter is string.ascii_uppercase:
            has_uppercase = True
          elif letter is string.ascii_lowercase:
            has_lowercase = True
          elif letter.isdigit():
            has_number = True
          elif letter is string.punctuation:
            has_symbol = True

      if not has_uppercase:
        print("Password must contain at least one uppercase letter.")
      if not has_lowercase:
        print("Password must contain at least one lowercase letter.")
      if not has_number:
        print("Password must contain at least one number letter.")
      if not has_symbol:
        print("Password must contain at least one symbol letter.")

      if has_uppercase and has_lowercase and has_number and has_symbol:
        print("Your password is valid!")
        break

    input_password = input("Password: ")

  print("Done!")

get_password()



import string

def get_password():
    password_input = input("Password: ")

    while True:
        has_uppercase = False
        has_lowercase = False
        has_digit = False
        has_symbol = False

        if len(password_input) < 4:
            print("Password must be at least eight characters long.")
        else:
            for letter in password_input:
                if letter in string.ascii_uppercase:
                    has_uppercase = True
                elif letter in string.ascii_lowercase:
                    has_lowercase = True
                elif letter.isdigit():
                    has_digit = True
                elif letter in string.punctuation:
                    has_symbol = True

            if not has_uppercase:
                print("Password must contain at least one uppercase letter.")
            if not has_lowercase:
                print("Password must contain at least one lowercase letter.")
            if not has_digit:
                print("Password must contain at least one digit.")
            if not has_symbol:
                print("Password must contain at least one symbol.")

            if has_uppercase and has_lowercase and has_digit and has_symbol:
                print("Password is valid.")
                break

        password_input = input("Password: ")

    print("Done!")

get_password()

